[project]
name = "ui"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mediapipe>=0.10.35",
    "numpy>=2.4.4",
    "opencv-python>=4.13.0.92",
    "pyopengl>=3.1.10",
    "pyqt5>=5.15.11",
    "pyqtgraph>=0.14.0",
    "pyside6>=6.11.0",
    "tensorflow[and-cuda]>=2.21.0",
]
